services:
  db:
    image: postgres
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_dummy
    ports:
      - "5432:5432"
#     volumes:
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
