services:
  postgres:
    container_name: postgres_keycloak
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: keycloakdb
    ports:
      - 5433:5432
#     networks:
#       - backend
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    restart: always
    volumes:
      ./realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloakdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    depends_on:
      - postgres
    ports:
      - 8081:8080
    command:
      - start-dev
#     networks:
#       - backend

# networks:
#   backend:
#     name: backend
#     driver: bridge
