services:
  mongodb:
    image: mongo
    container_name: db_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db_dummy
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data:
